name: pandahub

on:
  [push, pull_request]

jobs:
  build_ubuntu:
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
        os: [macos-latest, ubuntu-latest, windows-latest]
        panda-family: [e2nIEE/pandapower.git, e2nIEE/pandapipes.git]
        pandapower-version: &pp ['2.10.1', '2.10.0']
        pandapipes-version: &pps ['0.7.0', '0.6.0']
        panda-version: [*pp, *pps]
    runs-on: ${{ matrix.version }}
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        repository: ${{ matrix.panda-family}}
        ref: ${{matrix.pandapower-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install .["all"]
    - name: List of installed packages
      run: |
        pip list
    - name: Test with pytest and Codecov
      run: |
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
